URL: http://10.172.64.202:8888/#/login

USER_NAME:
PASSWORD:

MYSQL_DB_HOST:
MYSQL_DB_PORT:
MYSQL_DB_USER_NAME:
MYSQL_DB_USER_PASSWORD:
MYSQL_DB_DBNAME:

MSSQL_DB_HOST:
MSSQL_DB_USER_NAME:
MSSQL_DB_USER_PASSWORD:
MSSQL_DB_DBNAME: