URL: http://10.172.64.202:8888/#/login

FA_USER_NAME:
FA_PASSWORD:

DC_USER_NAME:
DC_PASSWORD:

RA_USER_NAME:
RA_PASSWORD:

TAX_USER_NAME:
TAX_PASSWORD:

YCJ_USER_NAME:
YCJ_PASSWORD:

Mysql_DB_HOST:
Mysql_DB_PORT:
Mysql_DB_USER_NAME:
Mysql_DB_USER_PASSWORD:
Mysql_DB_DBNAME:

Sql_Server_DB_HOST:
Sql_Server_DB_PORT:
Sql_Server_DB_USER_NAME:
Sql_Server_DB_USER_PASSWORD:
Sql_Server_DB_DBNAME: